weather = "sunny"
case weather
when "rainy"
    puts "Make sure you put on your gortex"
when "windy"
    puts "Hold on for dear life, and wear a wind-resistent jacket"
when "sunny"    
    puts "Smile and wear the shades bro"
when "cloudy"
    puts "Beware, it might rain so stay indoors or bring out the buckets"
when "snowy"
    puts "Put on the boots, and let the snowball fight begin"
when "foggy"
    puts "Beanie, scarf around neck and mouth, head down, enjoy the limited visibility"
else
    puts "Use common sense, never hurts to be unprepared."